version: '3'

services:
  workspace:
    container_name: medicine_workspace
    restart: always
    build: ./dockers/workspace
    volumes:
      - ./:/var/www/laravel
    tty: true
    networks:
      - mynet
  php-fpm:
    container_name: medicine_php-fpm
    restart: always
    build: dockers/php-fpm
    volumes:
      - ./:/var/www/laravel
    networks:
      - mynet
  nginx:
    container_name: medicine_nginx
    restart: always
    build: ./dockers/nginx
    volumes:
      - ./:/var/www/laravel
      - .docker/logs/nginx:/var/log/nginx
    ports:
      - "2019:80"
    networks:
      - mynet
  mysql:
    container_name: medicine_mysql
    restart: always
    image: mysql:5.7
    volumes:
      - .docker/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: medicine
      MYSQL_ROOT_PASSWORD: root
    networks:
      - mynet
  redis:
    container_name: medicine_redis
    restart: always
    image: redis
    networks:
      - mynet
networks:
  mynet:
    driver: bridge
volumes:
  db-data:
